//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        public int PlayerID { get; set; }
        public Nullable<bool> Skin1 { get; set; }
        public Nullable<bool> Skin2 { get; set; }
        public Nullable<bool> Skin3 { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
