//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int RecordID { get; set; }
        public int PlayerID { get; set; }
        public string Login { get; set; }
        public int Points { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
